---

- name: Install prerequisites
  yum:
    name: 'yum-utils'
    state: installed

- name: Configure Nginx repository
  yum_repository:
    name: 'nginx-stable'
    description: 'nginx stable repo'
    baseurl: "{{ nginx_centos_repo }}"
    gpgcheck: yes
    enabled: yes
    gpgkey: 'https://nginx.org/keys/nginx_signing.key'

- name: Install Nginx
  yum:
    name: nginx
    state: installed
  notify: 'Start Nginx'

- name: Enable the service
  service:
    name: nginx
    enabled: yes
  notify: 'Start Nginx'
